[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "retail_platform"
version = "0.1.0"
description = "Retail Analytics Platform Package"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "psycopg2-binary",
    "dbt-bigquery",
    "apache-airflow",
    "pytest",
    "kagglehub",
    "python-dotenv",
]
